### ISSUE TITLE
nextPwm should be shift

### ISSUE THREAD

**Issue by gewoods3** [ArminJo/Talkie#14]
https://github.com/ArminJo/Talkie/blob/c9672ef4c0b33df5ae614afbf399718677d3ec6a/src/Talkie.cpp#L847

This might be a bug, but it does not fix the Feather MO problem.

```c
    nextPwm = (u0 * 2) + 0x800;
```
should be
```c
    nextPwm = (u0 << 2) + 0x800;
```

**Comment by ArminJo** [comment]
Thanks for reporting 👍
