### ISSUE TITLE
Compiling on Arduino MKR 1010 WIFI giving Error

### ISSUE THREAD

**Issue by Lordsun-eng** [ArminJo/Talkie#16]
`
Arduino: 1.8.15 (Windows Store 1.8.49.0) (Windows 10), Board: "Arduino MKR WiFi 1010"

Documents\Arduino\libraries\Talkie\src\Talkie.cpp: In constructor 'Talkie::Talkie()':

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:281:17: error: 'DAC0' was not declared in this scope

 #define DAC_PIN DAC0   // pin 14/A0 for Zero. PA02 + DAC1 on due
\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:457:28: note: in expansion of macro 'DAC_PIN'
    NonInvertedOutputPin = DAC_PIN; // initialize with DAC pin

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:281:17: note: suggested alternative: 'PAC0'

 #define DAC_PIN DAC0   // pin 14/A0 for Zero. PA02 + DAC1 on due

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:457:28: note: in expansion of macro 'DAC_PIN'

     NonInvertedOutputPin = DAC_PIN; // initialize with DAC pin

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp: In constructor 'Talkie::Talkie(bool, bool)':

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:281:17: error: 'DAC0' was not declared in this scope

 #define DAC_PIN DAC0   // pin 14/A0 for Zero. PA02 + DAC1 on due

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:470:32: note: in expansion of macro 'DAC_PIN'

         NonInvertedOutputPin = DAC_PIN; // initialize with DAC pin

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:281:17: note: suggested alternative: 'PAC0'

 #define DAC_PIN DAC0   // pin 14/A0 for Zero. PA02 + DAC1 on due

\Documents\Arduino\libraries\Talkie\src\Talkie.cpp:470:32: note: in expansion of macro 'DAC_PIN'

         NonInvertedOutputPin = DAC_PIN; // initialize with DAC pin

exit status 1

Error compiling for board Arduino MKR WiFi 1010.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by ArminJo** [comment]
Thanks for reporting!
I released a new version 1.3.1, which fixes this problem
