### ISSUE TITLE
Compatibility with ATmega4809

### ISSUE THREAD

**Issue by kingKzK** [ArminJo/Talkie#19]
Arduino Nano Every has 16 Bit Timers (5 actually) and its more "powerful" than ATmega32u4 (16mhz vs 20mhz). And works on 32u4...

is there any way to make it work on the 4809?

**Comment by ArminJo** [comment]
You just have to modify the Talkie::initializeHardware() function 😀. It contains a lot of examples for different platforms.

**Comment by FuzzkingCool** [comment]
@kingKzK Did you ever get this to work? If so, would it be possible to share or put in as Pull Request? Cheers :)
