### ISSUE TITLE
List of words in talkie library

### ISSUE THREAD

**Issue by chau-ba-thong** [ArminJo/Talkie#20]
Hi, can you give me the content, or send me a link to get the list of words  in talkie lib that can be used in program? beside some words in the examples, i don't know which word can be used.
thanks

**Comment by ArminJo** [comment]
## Predefined vocabulary
The predefined vocabulary can be found in the [Vocab\_\*.h files](https://github.com/ArminJo/Talkie/blob/master/src), especially in [Vocab_US_Large.h](https://github.com/ArminJo/Talkie/blob/master/src/Vocab_US_Large.h).

**Comment by chau-ba-thong** [comment]
Got it, thanks!
