### ISSUE TITLE
Talkie cannot work with servo library

### ISSUE THREAD

**Issue by kengberg** [ArminJo/Talkie#27]
Hi

If you #include <Servo.h>

Try to make the Arduino Uno voice.say() something - the myservo.write(0) doesn't work.

It compiles and uploads fine, and other things work, but the servo doesn't move.

I don't get errors, but this reddit thread ([https://www.reddit.com/r/arduino/comments/7ea4ir/unknown_error_in_code_help/](RedditThread)) mentions a duplicate _vector11_ definition.

I'm a newbie, so I have no chance at fixing this, but perhaps you could?

Regards
       Kasper

**Comment by ArminJo** [comment]
> duplicate _vector11_ definition

Yes, you are on the right track.
