### ISSUE TITLE
no output using teensy 3.2

### ISSUE THREAD

**Issue by gretel** [ArminJo/Talkie#4]
version 1.0.2 (1.0.3 not released?) gives no output. tried changing pin declaration manually without effect.
the original library from paul stoffregen works fine, on pin `A14` (`DAC`).
i'd be glad if this library could work as a drop-in-replacement. thank you!

**Comment by ArminJo** [comment]
I will have a look.

**Comment by ArminJo** [comment]
I installed with tensiduino installer and there is no original talkie library 😢 
But my sources are compiling and I made a few changes. But I am not finished yet.

**Comment by gretel** [comment]
uh "original" was a bit far fetched.. this one

https://github.com/PaulStoffregen/Talkie

**Comment by ArminJo** [comment]
I uploaded the "final" version for Teensy.
Can you please test it and give feedback.
Then I can build a new Arduino library release.

**Comment by ArminJo** [comment]
I just fixed a bug and updated the repo.

**Comment by gretel** [comment]
@ArminJo thank you. going to report back.
