### ISSUE TITLE
Terrible advice

### ISSUE THREAD

**Issue by jremington** [ArminJo/Talkie#5]
`I use the speakers from old earphones or headphones, which have approximately 16 to 32 Ohm, directly without a series resistor. `

In other words, "how to destroy your Arduino".

**Comment by ArminJo** [comment]
Have you ever tested it?

**Comment by jremington** [comment]
I'm not so stupid as to intentionally violate the absolute maximum pin current ratings, but I imagine it will work for a while.

**Comment by jbarth-ubhd** [comment]
Yes, I would at least take 100 Ω and a (NPN) BC337-40 (better with together with a (PNP) BC327-40 and both emitters connected to a 1000 µF output capacitor).
