### ISSUE TITLE
Set pitch

### ISSUE THREAD

**Issue by ErikOostveen** [ArminJo/Talkie#50]
Great job in keeping talkie going!

I would love to see a way of adding the sample rate to the say function - so say(<word>,6000) would play slower and say(<word>,10000) faster with 8000 being the default when not given --- how difficult would this to implement?

**Comment by ArminJo** [comment]
Can you first test it?
1. Change #define SAMPLE_RATE 8000 // Speech engine sample rate to the value you want
2. Change #define ISR_RATIO (25000/ (1000000 / SAMPLE_RATE) ) to #define ISR_RATIO 200
3. Test it if it works and the effect is reasonable.

**Comment by ErikOostveen** [comment]
Thanks for getting back to quickly!

That test works nicely (I tried 4000 to 16000)

**Comment by deladriere** [comment]
Hi Erik also check this one derived from my Talko : it add speed / pitch / and toy bending 😉
https://github.com/technologiescollege/ArduinoTechnoEduc/blob/master/portable/sketchbook/libraries/Talkietz/talkietz.h

**Comment by ArminJo** [comment]
@ErikOostveen 
Done 😀
Can you please test the new library version from this repo?
I added parameter `aSampleRateForPitch `.

**Comment by ErikOostveen** [comment]
Nice one @ArminJo 

It took me a little while to realize I had to Enable pitch for it to work but after that it seems to work well. Adding these features makes the library instantly more attractive for folks like me looking for ways to manipulate sound :-)

I"ll also have a look at @deladriere

**Comment by ArminJo** [comment]
@ErikOostveen 
Plese give me feedback, if the speed and bending features of deladriere's version makes sense for folks like you.
I currently habe not time to test this features for myself.

**Comment by ErikOostveen** [comment]
> Hi Erik also check this one derived from my Talko : it add speed / pitch / and toy bending 😉 https://github.com/technologiescollege/ArduinoTechnoEduc/blob/master/portable/sketchbook/libraries/Talkietz/talkietz.h and the example https://github.com/technologiescollege/ArduinoTechnoEduc/blob/master/portable/sketchbook/libraries/Talkietz/examples/demo/demo.ino

That was worth looking at - I like being able to also set speed and distortion - with distortion sounding like putting a voice through a rindmodulator - nice work @deladriere !

... so, @ArminJo the library could use adding those two parameters as well - and what about an on-the-fly reverse-speech option?  :-)
