### ISSUE TITLE
How do I make the program dynamic

### ISSUE THREAD

**Issue by suraj-b** [ArminJo/Talkie#7]
I have been trying to use this library and make it dynamic. What I'm trying to do is receive data from another arduino, say the keyword *DANGER*, and pass it through the in-built function voice.say(). I do understand that the voice.say() accepts uint_8t datatype. Any help is greatly appreciated.

**Comment by ArminJo** [comment]
Best is you study the code, then you will find the answers.

**Comment by suraj-b** [comment]
Is there a way I could pass the arguements to voice.say() using a loop?

**Comment by suraj-b** [comment]
I think what we can do is take the address of the array, lets say of DANGER,  from program memory and map the address to its respective word. Whenever a word is detected in user input we can point to the address in voice.say(). Can this be done?

**Comment by ArminJo** [comment]
Of course this can be done, but keep in mind that every word is precompiled and can not created at runtime. Takie is NO text to speech engine.
