### ISSUE TITLE
Where to change code for Mega2560

### ISSUE THREAD

**Issue by LtInPB** [ArminJo/Talkie#9]
This Talkie software looks very promising to me.  

On compiling with IDE and for a Mega2560, this error appears: Error compiling for board Arduino Mega or Mega 2560

The code says:  ATmega2560: non inverted at pin 6, inverted at pin 7

Question: where in the code do the changes go?

Thank you

**Comment by ArminJo** [comment]
I am sorry, but there is no error for me when compiling for Arduino Mega or Mega 2560.

**Comment by LtInPB** [comment]
*Thank you for your response.*
*Testing more...  did not have to change any code*
*I just needed to change the speaker wire to pin 6 or 7 *

**Comment by ArminJo** [comment]
Yepp, thats right 👍
